// angular-applcation/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'final';
  myForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.myForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
    });
  }

  submit(): void {
    if (this.myForm.valid) console.log(this.myForm.value);
    else console.log("Invalid input");
  }
}

<div class="form-container">
  <form [formGroup]="myForm" (ngSubmit)="submit()">
    <input placeholder="Name" formControlName="name"/>
    <input placeholder="Email" formControlName="email"/>
    <button type="submit">Submit</button>
    <button type="reset">Cancel</button>
  </form>
</div>

// react-application/src/App.js
import logo from './logo.svg';
import './App.css';
import { useState } from 'react';

function App() {
  const [myForm, setMyForm] = useState({
    name: '',
    email: ''
  });

  const handleInputChange = (event) => {
    const{name, value} = event.target;
    console.log(name, value);
    setMyForm({
      ...myForm,
      [name]: value,
    });
  };

  const submit = (event) => {
    event.preventDefault();
    console.log(myForm);
  };

  return (
    <form onClick={submit}>
    <input onChange={handleInputChange} name="name" placeholder="Name" />
    <input onChange={handleInputChange} name="email" placeholder="Email" />
    <button type="submit">Submit</button>
    <button type="reset">Cancel</button>
  </form>
  );
}

export default App;
