// react-form/src/App.js
import './App.css';
import { useState } from 'react';

function App() {
  const [formData, setFormData] = useState({
    name: '',
    email: ''
  });

  const handleInput = (e) => {
    const {name, value } = e.target
    console.log(name, value)
    setFormData({
      ...formData,
      [name]: value
    })
  }

  const submit = (e) => {
    e.preventDefault();
    console.log(formData);
  }

  return (
    <form>
      <input onChange={handleInput} name="name" placeholder="name" />
      <input onChange={handleInput} name="email" placeholder="email" />
      <button onClick={submit} type="submit">Submit</button>
    </form>
  )
}

export default App;

// angular-form/src/app/app.component.ts
import { Component } from "@angular/core";
import { FormBuilder, FormGroup, Validators } from "@angular/forms";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "angular-form";
  myForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.myForm = this.fb.group({
      name: ["", Validators.required],
      email: ["", [Validators.required, Validators.email]],
    });
  }

  submit(): void {
    if (this.myForm.valid) console.log(this.myForm.value);
  }
}

<form [formGroup]="myForm" (ngSubmit)="submit()">
  <input formControlName="name" placeholder="Name" />
  <input formControlName="email" placeholder="Email" />
  <button type="submit">Submit</button>
</form>
